baseURL = 'https://blog.arwalk.net'
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "Arwalk's blog"
theme = "hugo-coder"

[security.exec]
allow = "asciidoctor"

[markup.asciidocExt.attributes]
source-highlighter = 'rouge'
rouge-css = "style"
rouge-style = "monokai.sublime"

[params]
  author = "Arwalk"
  info = "My stuff i guess"
  description = "Arwalk's blog"
  keywords = "blog,developer,personal"
  gravatar = "siragentprovocateurarwalk@gmail.com"

  
  
  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

[sitemap]
  changefreq = "always"
  filename = "sitemap.xml"
  priority = 0.5